import pandas as pd


# 1. Sample dataset
data = {
    "messages": [
        {"message": "When will my order be delivered?", "category": "Inquiry"},
        {"message": "I want to know the status of my refund.", "category": "Inquiry"},
        {"message": "The product arrived damaged.", "category": "Complaint"},
        {"message": "The delivery is delayed again!", "category": "Complaint"},
        {"message": "Great customer service!", "category": "Feedback"},
        {"message": "I love your quick response time!", "category": "Feedback"},
        {"message": "Can you help me change my address?", "category": "Request"},
        {"message": "Please update my phone number.", "category": "Request"},
        {"message": "Where can I track my shipment?", "category": "Inquiry"},
        {"message": "The item I received is incorrect.", "category": "Complaint"},
        {"message": "Kudos to your team!", "category": "Feedback"},
        {"message": "I would like to cancel my order.", "category": "Request"},
        {"message": "Why is my payment still pending?", "category": "Inquiry"},
        {"message": "Received wrong item, very disappointed.", "category": "Complaint"},
        {"message": "Amazing shopping experience!", "category": "Feedback"},
        {"message": "Can you provide an estimated delivery date for my order?", "category": "Inquiry"},
        {"message": "Has my payment been successfully processed?", "category": "Inquiry"},
        {"message": "Is this item available for purchase?", "category": "Inquiry"},
        {"message": "What are the warranty details for this product?", "category": "Inquiry"},
        {"message": "How do I apply a discount code to my purchase?", "category": "Inquiry"},
        {"message": "My package arrived late, and I am not happy about it.", "category": "Complaint"},
        {"message": "The quality of the item does not match the description.", "category": "Complaint"},
        {"message": "I received a defective product—what should I do next?", "category": "Complaint"},
        {"message": "I was charged incorrectly—please fix this issue.", "category": "Complaint"},
        {"message": "The customer service response time is too slow.", "category": "Complaint"},
        {"message": "Your platform is user-friendly and easy to navigate!", "category": "Feedback"},
        {"message": "I appreciate how seamless the checkout process was.", "category": "Feedback"},
        {"message": "The packaging was excellent—no damages at all!", "category": "Feedback"},
        {"message": "Your team handled my issue efficiently—thank you!", "category": "Feedback"},
        {"message": "I'm impressed by your wide range of product choices.", "category": "Feedback"},
        {"message": "I need assistance with updating my billing information.", "category": "Request"},
        {"message": "Can I reschedule my delivery for a different date?", "category": "Request"},
        {"message": "Please help me apply a gift card to my order.", "category": "Request"},
        {"message": "I want to change the color of the item I ordered.", "category": "Request"},
        {"message": "Can I add an extra item to my existing order?", "category": "Request"},
        {"message": "I need help resetting my account password.", "category": "Request"},
        {"message": "The app keeps crashing when I try to open it.", "category": "Complaint"},
        {"message": "Thank you for the prompt delivery!", "category": "Feedback"},
        {"message": "How do I return an item I purchased?", "category": "Inquiry"},
        {"message": "My order was cancelled without explanation.", "category": "Complaint"},
        {"message": "Excellent packaging and fast shipping.", "category": "Feedback"},
        {"message": "Can I get an invoice for my last purchase?", "category": "Request"},
        {"message": "Is there a warranty on electronics?", "category": "Inquiry"},
        {"message": "The replacement item was also defective.", "category": "Complaint"},
        {"message": "Very satisfied with your service.", "category": "Feedback"},
        {"message": "I need a replacement for my broken charger.", "category": "Request"},
        {"message": "The website is not loading on my browser.", "category": "Complaint"},
        {"message": "Your staff was very polite and helpful.", "category": "Feedback"},
        {"message": "How do I update my shipping address?", "category": "Inquiry"},
        {"message": "I want to unsubscribe from promotional emails.", "category": "Request"},
        {"message": "The payment gateway failed during checkout.", "category": "Complaint"},
        {"message": "Loved the packaging and presentation!", "category": "Feedback"},
        {"message": "Can I change my delivery slot?", "category": "Request"},
        {"message": "Is there a return policy for electronics?", "category": "Inquiry"},
        {"message": "Received an empty box, please assist.", "category": "Complaint"},
        {"message": "The app interface is very user-friendly.", "category": "Feedback"},
        {"message": "How do I track my refund status?", "category": "Inquiry"},
        {"message": "I want to delete my account.", "category": "Request"},
        {"message": "The product was missing accessories.", "category": "Complaint"},
        {"message": "Thank you for resolving my issue quickly.", "category": "Feedback"},
        {"message": "Can I get a call back from support?", "category": "Request"},
        {"message": "Is there a student discount available?", "category": "Inquiry"},
        {"message": "The delivery person was rude.", "category": "Complaint"},
        {"message": "Appreciate the fast response from your team.", "category": "Feedback"},
        {"message": "How do I change my payment method?", "category": "Inquiry"},
        {"message": "I want to pause my subscription.", "category": "Request"},
        {"message": "Received a used product instead of new.", "category": "Complaint"},
        {"message": "Great offers and deals on your platform!", "category": "Feedback"},
        {"message": "Can I split my order into two shipments?", "category": "Request"},
        {"message": "Is there a loyalty program?", "category": "Inquiry"},
        {"message": "The product color is different from the image.", "category": "Complaint"},
        {"message": "Very happy with the after-sales service.", "category": "Feedback"},
        {"message": "How do I activate my warranty?", "category": "Inquiry"},
        {"message": "I want to update my email address.", "category": "Request"},
        {"message": "The order was delivered to the wrong address.", "category": "Complaint"},
        {"message": "Thank you for the birthday discount!", "category": "Feedback"},
        {"message": "Can I get a digital copy of my invoice?", "category": "Request"},
        {"message": "Is there a way to expedite shipping?", "category": "Inquiry"},
        {"message": "Received a product with expired warranty.", "category": "Complaint"},
        {"message": "Loved the eco-friendly packaging.", "category": "Feedback"},
        {"message": "How do I redeem my reward points?", "category": "Inquiry"},
        {"message": "I want to change my subscription plan.", "category": "Request"},
        {"message": "The product was not as described.", "category": "Complaint"},
        {"message": "Excellent customer support experience.", "category": "Feedback"},
        {"message": "Can I get a replacement instead of refund?", "category": "Request"},
        {"message": "Is there a helpline for urgent issues?", "category": "Inquiry"},
        {"message": "The delivery was rescheduled without notice.", "category": "Complaint"},
        {"message": "Appreciate the regular order updates.", "category": "Feedback"},
        {"message": "How do I check my order history?", "category": "Inquiry"},
        {"message": "I want to add a new address to my profile.", "category": "Request"},
        {"message": "Received a product with missing parts.", "category": "Complaint"},
        {"message": "Great job on the festive packaging!", "category": "Feedback"},
        {"message": "Can I get a GST invoice?", "category": "Request"},
        {"message": "Is there a way to contact the seller directly?", "category": "Inquiry"},
        {"message": "The product was delivered late at night.", "category": "Complaint"},
        {"message": "Very pleased with the product quality.", "category": "Feedback"},
        {"message": "How do I cancel my subscription?", "category": "Request"},
        {"message": "I want to change my preferred language.", "category": "Request"},
        {"message": "The product was not sealed properly.", "category": "Complaint"},
        {"message": "Thank you for the free sample!", "category": "Feedback"},
        {"message": "Can I get a price match on my order?", "category": "Request"},
        {"message": "Is there a referral program?", "category": "Inquiry"},
        {"message": "Received a product with scratches.", "category": "Complaint"},
        {"message": "Loved the handwritten thank you note.", "category": "Feedback"},
        {"message": "How do I update my contact number?", "category": "Inquiry"},
        {"message": "I want to opt out of SMS notifications.", "category": "Request"},
        {"message": "The product was not packed securely.", "category": "Complaint"},
        {"message": "Great deals during the sale!", "category": "Feedback"},
        {"message": "Can I get a demo before purchase?", "category": "Request"},
        {"message": "Is there a way to track the delivery person?", "category": "Inquiry"},
        {"message": "Received a product with a broken seal.", "category": "Complaint"},
        {"message": "Very impressed with the quick delivery.", "category": "Feedback"},
        {"message": "How do I change my account password?", "category": "Inquiry"},
        {"message": "I want to merge two accounts.", "category": "Request"},
        {"message": "The product was not delivered as promised.", "category": "Complaint"},
        {"message": "Thank you for the loyalty bonus!", "category": "Feedback"},
        {"message": "Can I get a call from a product expert?", "category": "Request"},
        {"message": "Is there a way to get early access to sales?", "category": "Inquiry"},
        {"message": "Received a product with a manufacturing defect.", "category": "Complaint"},
        {"message": "Loved the festive discount offers.", "category": "Feedback"},
        {"message": "How do I check my wallet balance?", "category": "Inquiry"},
        {"message": "I want to update my profile picture.", "category": "Request"},
        {"message": "The product was not delivered on time.", "category": "Complaint"},
        {"message": "Thank you for the personalized message!", "category": "Feedback"},
        {"message": "Can I get a replacement for a defective item?", "category": "Request"},
        {"message": "Is there a way to get a faster refund?", "category": "Inquiry"},
        {"message": "Received a product with a missing manual.", "category": "Complaint"},
        {"message": "Very happy with the packaging quality.", "category": "Feedback"},
        {"message": "How do I check my loyalty points?", "category": "Inquiry"},
        {"message": "I want to change my registered email.", "category": "Request"},
        {"message": "The product was not as per the description.", "category": "Complaint"},
        {"message": "Thank you for the quick exchange process!", "category": "Feedback"},
        {"message": "Can I get a call from customer care?", "category": "Request"},
        {"message": "Is there a way to get a paper bill?", "category": "Inquiry"},
        {"message": "Received a product with a torn label.", "category": "Complaint"},
        {"message": "Loved the easy checkout process.", "category": "Feedback"},
        {"message": "How do I update my delivery instructions?", "category": "Inquiry"},
        {"message": "I want to change my default address.", "category": "Request"},
        {"message": "The product was not delivered in good condition.", "category": "Complaint"},
        {"message": "Thank you for the festive greetings!", "category": "Feedback"},
        {"message": "Can I get a call from the delivery agent?", "category": "Request"},
        {"message": "Is there a way to get a digital receipt?", "category": "Inquiry"},
        {"message": "Received a product with a damaged box.", "category": "Complaint"},
        {"message": "Very satisfied with the overall experience.", "category": "Feedback"}
    ]
}

# 2. Convert to DataFrame
df = pd.DataFrame(data["messages"])

# 3. Save DataFrame to CSV
df.to_csv("data.csv", index=False)